language: java
jdk:
  - openjdk8

sudo: required
install: true

jobs:
  include:
    - stage: test
      script:
        - if [ -z "$CLIENT_ID" ]; then
            travis_terminate 0
          fi
        - mvn clean package -DskipTests